server:
 port: 8888
spring:
 application:
  name: configservice
 cloud:
  config:
   server:
    git:
     uri: https://github.com/psuday/springconfig.git
     searchPaths: appointmentservice
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka

